### PR TITLE
Run the app as localhost

### PR DESCRIPTION
**Pull request by Sim4n6**
I believe no need to expose it to the lan.

### CODE REVIEW

**Comment by PatrikFehrenbach** [comment]
Unfortunately, this doesn't work for me.  It won't forward the port i guess due to the fact that its not using a WSGI server and is running in dev mode

**Comment by Sim4n6** [comment]
it is working. using `127.0.0.1` rather than `0.0.0.0` would make it accessible locally. I don't see what is the problem , I fire up `sudo docker-compose up` after deleting the containers and the images and it is working. Could you please consider again ? or tell me in details what's the problem, please.

 thank you

**Comment by PatrikFehrenbach** [comment]
The solution is to expose the Port in flask: 

```
if __name__ == "__main__":
    app.run(debug=True, host="0.0.0.0", port=5000)
``` 

and limit the accessability to localhost in the docker-compose: 

```
  web:
    build: .
    ports:
      - 127.0.0.1:5000:5000  # Bind to localhost only
    depends_on:
      - mongodb
    environment:
      - FLASK_RUN_HOST=0.0.0.0  # Listen on all interfaces
```

could you give this a try?

**Review by PatrikFehrenbach — APPROVED** [review]
Yep looks good!

**Comment by Sim4n6** [comment]
Sorry, about the little mess in this PR. I have to set up a new branch for each feature. 

Anyway, I reverted back the change so the PR could be merged. 

Could you please do this for me: 
 - set up a **road map** for the project in GitHub, this project looks interesting and I would like to contribute more <https://github.blog/changelog/2023-01-31-roadmap-in-projects-public-beta/>
 - enable private vulnerability reporting <https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository>

**Pull request merged**
